# ==========================================
# CONEXIÓN A SUPABASE (PostgreSQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://db.anemjyacnnxrnpqsyvaz.supabase.co:5432/postgres?user=postgres&password=[YOUR-PASSWORD]    
spring.datasource.username=postgres
spring.datasource.password=644BHZo2rJtR8IAU25XTs88gX6ugUQXeZh7YSN7KkBaQi8QeH1VTm06dB13IPYYvHiTymAFJhYT0MBIDDLSJkkxUE7YyFh2WytQ
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# SWAGGER / SPRINGDOC
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ==========================================
# SERVIDOR
# ==========================================
server.port=8080
spring.application.name=futbolapi